#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint-staged

# # user.nameの確認
# if [ "`git config --local user.name`" != "vercel-bike-startup"  ]; then
#   echo "fatal: user.name is not set correctly"
#   exit 1
# fi

# # user.emailの確認
# if [ "`git config --local user.email`" != "vercel@bike-startup.co.jp"  ]; then
#   echo "fatal: user.email is not set correctly"
#   exit 1
# fi
