name: lighthouse
on:
  pull_request:
    types:
      - opened
    branches:
      - "main"
env:
  NEXT_PUBLIC_WORDPRESS_URL: ${{secrets.NEXT_PUBLIC_WORDPRESS_URL}}
jobs:
  lhci:
    name: lighthouse-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 17
        uses: actions/setup-node@v2
        with:
          node-version: "17"
          cache: "yarn"
      - name: yarn install, build
        run: |
          yarn install
          yarn build
      - name: run Lighthouse CI
        run: |
          yarn lhci
