name: lighthouse
on: [push]
env:
  NEXT_PUBLIC_WORDPRESS_URL: ${{secrets.NEXT_PUBLIC_WORDPRESS_URL}}
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: yarn install, build
        run: |
          rm -rf node_modules
          yarn --frozen-lockfile
          yarn build
      - name: run Lighthouse CI
        run: |
          yarn global add @lhci/cli@0.8.x
          lhci autorun
